language: node_js
sudo: false
node_js:
  - "10.5.0"
before_install:  
  - node -v && npm -v
  - npm install -g npx
install:
  - npm install
script:
  - npm run lint_src
  - npm run lint_spec
  - npm run lint_examples
  - npm test
after_success:
  - npm run coverage
